project:
  type: book

book:
  title: A Quarto PDF book on very long headings in headers
  date: 2025-11-03
  chapters:
    - index.qmd
    - intro.qmd
    - chapter_1.qmd
    - chapter_2.qmd

format:
  pdf:
    documentclass: scrbook
    toc: true
    mainfont: Arial



